site_name: Cluster Experiments Docs
extra_css: [style.css]
repo_url: https://github.com/david26694/cluster-experiments
site_url: https://david26694.github.io/cluster-experiments/
site_description: Functions to design and run clustered experiments
site_author: David Masip
use_directory_urls: false
edit_uri: blob/main/docs/
nav:
  - Home:
    - Index: index.md
  - Cupac example: cupac_example.ipynb
  - Custom classes: create_custom_classes.ipynb
  - Switchback:
      - Stratified switchback: switchback.ipynb
      - Switchback calendar visualization: plot_calendars.ipynb
      - Visualization - 4-hour switches: plot_calendars_hours.ipynb
  - Multiple treatments: multivariate.ipynb
  - AA test clustered: aa_test.ipynb
  - Paired T test: paired_ttest.ipynb
  - API:
      - Experiment analysis: api/experiment_analysis.md
      - Perturbators: api/perturbator.md
      - Splitter: api/random_splitter.md
      - Pre experiment outcome model: api/cupac_model.md
      - Power config: api/power_config.md
      - Power analysis: api/power_analysis.md
      - Washover: api/washover.md
plugins:
  - mkdocstrings:
      watch:
        - cluster_experiments
  - mkdocs-jupyter
  - search
copyright: Copyright &copy; 2022 Maintained by David Masip.
theme:
  name: material
  font:
    text: Ubuntu
    code: Ubuntu Mono
  feature:
    tabs: true
  palette:
    primary: indigo
    accent: blue
markdown_extensions:
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - toc:
      permalink: true
