name: Docs

on:
  push:
    branches:
    - main
    - fix-docs-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: cp README.md docs/index.md
      - run: cp -r theme docs/theme
      - run: make install-dev-gh-action
      - run: source .venv/bin/activate
      - run: pip install lxml_html_clean
      - run: which python
      - run: mkdocs gh-deploy --force
