name: Docs

on:
  push:
    branches:
    - main
    - cluster-experiments

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - run: cp README.md docs/index.md
      - run: cp -r theme docs/theme
      - run: |
          make install-dev-gh-action
          source .venv/bin/activate
          pip install lxml_html_clean
          mkdocs gh-deploy --force
