name: Docs test
# Test that the docs build correctly

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: cp README.md docs/index.md
      - run: cp -r theme docs/theme
      - run: make install-dev
      - name: Serve docs and check for errors
        run: |
          cp README.md docs/index.md
          rm -rf docs/theme
          cp -r theme docs/theme/
          mkdocs serve & sleep 10
          curl --fail http://127.0.0.1:8000 || (pkill mkdocs; exit 1)
          pkill mkdocs
