name: Release to PyPI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make install-dev

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: david26694
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: make pypi-gh-actions
